db:
  schema: TEST_SCHEMA
  audit:
    table: CONFIG_MAP
    mapping_table: COMFIG_MAP_AUDIT
    audit_mode: C,R,U,D
    audit_retention: 3 #month

spring:
  datasource:
    url: jdbc:h2:file:/data/demo_test
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


